# Generated by Django 4.2.18 on 2025-01-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=70)),
                ("year", models.IntegerField(default="")),
                ("name", models.CharField(default="", max_length=70)),
                ("list_id", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="BookList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=70)),
            ],
        ),
    ]
