# Generated by Django 4.2.18 on 2025-01-30 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_add_lists"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BookList",
        ),
    ]
