# Generated by Django 4.2.18 on 2025-01-31 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_add_books_lists_junction_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="Book",
                to="api.list",
            ),
        ),
    ]
